#!/bin/sh
# PHP CGI wrapper for AgentHTTPD. Generated by scripts/build-cgis.sh
# Runs cgi-langs/php/main.php via php-cgi. homebrew php-cgi is built with
# --enable-force-cgi-redirect, so REDIRECT_STATUS must be set.
APP_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/../cgi-langs/php" && pwd)
REDIRECT_STATUS=200
export REDIRECT_STATUS
SCRIPT_FILENAME="$APP_DIR/main.php"
export SCRIPT_FILENAME
exec php-cgi "$SCRIPT_FILENAME"
