#!/bin/sh
# Build all language CGI examples into cgi-bin/. Each toolkit is optional:
# if a compiler/interpreter is missing, its CGI is skipped (and staleness
# warnings suppressed by rm). Usage: sh scripts/build-cgis.sh

set -e
ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$ROOT"

mkdir -p cgi-langs/java/classes
mkdir -p cgi-bin

build_go() {
    if command -v go >/dev/null 2>&1; then
        echo "go: building cgi-bin/go.cgi"
        (cd cgi-langs/go && go build -o ../../cgi-bin/go.cgi main.go)
    else
        echo "go: skipped (not installed)"
    fi
}

build_rust() {
    if command -v rustc >/dev/null 2>&1; then
        echo "rust: building cgi-bin/rust.cgi"
        rustc --edition 2021 -O cgi-langs/rust/main.rs -o cgi-bin/rust.cgi
    else
        echo "rust: skipped (not installed)"
    fi
}

build_java() {
    if command -v javac >/dev/null 2>&1; then
        echo "java: compiling Main.class"
        javac --release 11 -d cgi-langs/java/classes cgi-langs/java/Main.java
        cat > cgi-bin/java.cgi <<'EOF'
#!/bin/sh
# Java CGI wrapper for AgentHTTPD. Generated by scripts/build-cgis.sh
APP_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/../cgi-langs/java/classes" && pwd)
exec java -cp "$APP_DIR" Main
EOF
        chmod +x cgi-bin/java.cgi
    elif command -v java >/dev/null 2>&1; then
        echo "java: skipped (javac not installed)"
    else
        echo "java: skipped (not installed)"
    fi
}

build_php() {
    if command -v php-cgi >/dev/null 2>&1; then
        echo "php: writing wrapper cgi-bin/php.cgi"
        cat > cgi-bin/php.cgi <<'EOF'
#!/bin/sh
# PHP CGI wrapper for AgentHTTPD. Generated by scripts/build-cgis.sh
# Runs cgi-langs/php/main.php via php-cgi. homebrew php-cgi is built with
# --enable-force-cgi-redirect, so REDIRECT_STATUS must be set.
APP_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/../cgi-langs/php" && pwd)
REDIRECT_STATUS=200
export REDIRECT_STATUS
SCRIPT_FILENAME="$APP_DIR/main.php"
export SCRIPT_FILENAME
exec php-cgi "$SCRIPT_FILENAME"
EOF
        chmod +x cgi-bin/php.cgi
    else
        echo "php: skipped (php-cgi not installed)"
    fi
}

build_ruby() {
    if command -v ruby >/dev/null 2>&1; then
        echo "ruby: copying cgi-bin/ruby.cgi"
    else
        echo "ruby: skipped (not installed)"
    fi
}

build_php
build_ruby
build_go
build_rust
build_java

cp cgi-langs/ruby/main.rb cgi-bin/ruby.cgi
chmod +x cgi-bin/*.cgi

echo "done."